name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Just testing
      shell: bash
      env:
        PISTON_API: ${{ secrets.PISTON_API }}
      run: echo $PISTON_API
