name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  PISTON_API: ${{ secrets.PISTON_API }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: PISTON_API=$PISTON_API cargo build --verbose
    - name: Run tests
      run: PISTON_API=$PISTON_API cargo test --verbose
