name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create .env file
      env:
        PISTON_API: ${{ secrets.PISTON_API }}
      run: echo "PISTON_API=$PISTON_API" > .env
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
